permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 王光东
  email: jsondream@gmail.com
  link: http://www.jsondream.com
  weibo: http://weibo.com/u/1829980775?is_all=1
  github: http://github.com/wgd12389

# 站点信息
title: 王光东的博客 
description: 王光东的博客
url: http://www.jsondream.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: www.jsondream.com

# disqus 设置
disqus:
  shortname: jsondream
